const result=document.getElementById('result'),thought=document.getElementById('thought'),resultText=document.getElementById('resultText'),modeLabel=document.getElementById('modeLabel'),codexId=document.getElementById('codexId'),codexType=document.getElementById('codexType'),codexCodename=document.getElementById('codexCodename'),saveCodex=document.getElementById('saveCodex'),historyList=document.getElementById('historyList'),codexPanel=document.getElementById('codexPanel'),enigmaPanel=document.getElementById('enigmaPanel'),lumenPanel=document.getElementById('lumenPanel'),translatorPanel=document.getElementById('translatorPanel'),graphPanel=document.getElementById('graphPanel'),aiCorePanel=document.getElementById('aiCorePanel');
const translationTarget=document.getElementById('translationTarget'),translationSource=document.getElementById('translationSource'),translationOriginal=document.getElementById('translationOriginal'),translationOutput=document.getElementById('translationOutput'),translationStatus=document.getElementById('translationStatus');
const modes={codex:['CODEX','O fragmento foi recebido como um novo registro potencial.'],enigma:['ENIGMA','Toda resposta contém outra pergunta.'],poeta:['POETA','A experiência pode ser reorganizada como linguagem: imagem, ritmo, metáfora e silêncio.'],arquiteto:['ARQUITETO','O pensamento pode ser decomposto em sinais, relações, causa e consequência.'],lumen:['LUMEN','Procure relações entre aquilo que foi dito e aquilo que ainda não foi nomeado.'],translator:['TRANSLATOR','A camada multilíngue preserva contexto e o texto original.'],graph:['CODEX GRAPH','As ideias deixam de ser ilhas e passam a formar uma arquitetura de relações.']};
function getHistory(){return JSON.parse(localStorage.getItem('nqc_codex_history')||'[]')}function setHistory(x){localStorage.setItem('nqc_codex_history',JSON.stringify(x))}function nextId(){return`CODEX-${String(getHistory().length+1).padStart(3,'0')}`}
function run(mode='lumen'){const value=thought.value.trim()||'Uma pergunta ainda não formulada.',[name,msg]=modes[mode]||modes.lumen;modeLabel.textContent=name;resultText.textContent=`“${value}” — ${msg}`;result.hidden=false;if(mode==='lumen')runLumen(value);result.scrollIntoView({behavior:'smooth',block:'center'})}
function runLumen(value){if(!window.LumenEngine)return;const out=LumenEngine.analyze({text:value,mode:'lumen',enigma:window.EnigmaEngine?.current||null});document.getElementById('lumenSynthesis').textContent=out.synthesis;document.getElementById('lumenLens').textContent=out.lens;document.getElementById('lumenQuestion').textContent=out.question;lumenPanel.hidden=false}
function renderHistory(){const items=getHistory();historyList.innerHTML=items.length?items.map(x=>`<button class="history-item" data-id="${x.id}"><b>${x.id}</b><span>${x.codename}</span><small>${x.type} · ${x.language}</small></button>`).join(''):'<p class="empty">Nenhum Códice salvo nesta sessão.</p>';historyList.querySelectorAll('.history-item').forEach(b=>b.onclick=()=>{const x=getHistory().find(i=>i.id===b.dataset.id);if(!x)return;thought.value=x.original;codexId.textContent=x.id;codexType.value=x.type;codexCodename.value=x.codename;run('codex')})}
function saveCurrent(){const original=thought.value.trim();if(!original){thought.focus();return}const x={id:nextId(),codename:codexCodename.value.trim()||'ARCANO / GENESIS',type:codexType.value,language:'pt-BR',original,createdAt:new Date().toISOString()};const items=getHistory();items.push(x);setHistory(items);codexId.textContent=x.id;renderHistory();run('codex')}
function showPanel(panel){[codexPanel,enigmaPanel,lumenPanel,translatorPanel,graphPanel,aiCorePanel].forEach(p=>{if(p)p.hidden=p!==panel});if(panel)panel.scrollIntoView({behavior:'smooth',block:'center'})}
function initTranslator(){if(!translationTarget||!window.TranslatorEngine)return;translationTarget.innerHTML=Object.entries(TranslatorEngine.getSupportedLanguages()).map(([c,n])=>`<option value="${c}">${n}</option>`).join('');translationTarget.value='en-US'}
function translateCurrent(){if(!window.TranslatorEngine)return;const value=thought.value.trim(),target=translationTarget.value,source=TranslatorEngine.detect(value),packet=TranslatorEngine.packet(value,target);translationSource.value=source?`${TranslatorEngine.getSupportedLanguages()[source]} (${source})`:'Não detectado';translationOriginal.textContent=value?`Original preservado · ${source}`:'Digite primeiro um fragmento no Codex.';translationOutput.textContent=packet.translation.text||'Sem conteúdo para traduzir.';translationStatus.textContent=packet.translation.status.toUpperCase();showPanel(translatorPanel)}
function renderGraph(){if(!window.CodexGraph)return;const s=CodexGraph.summary();document.getElementById('graphSummary').textContent=`${s.nodes} NÓS · ${s.edges} RELAÇÕES`;const list=document.getElementById('graphList'),edges=CodexGraph.all();list.innerHTML=edges.length?edges.map(e=>`<div class="history-item"><b>${e.from} → ${e.to}</b><span>${e.type}</span><small>${e.note||'sem nota'}</small></div>`).join(''):'<p class="empty">Nenhuma relação criada.</p>';if(window.GraphVisualizer)GraphVisualizer.render('graphCanvas')}
function connectGraph(){const e=CodexGraph.connect(document.getElementById('graphFrom').value.trim(),document.getElementById('graphTo').value.trim(),document.getElementById('graphType').value,document.getElementById('graphNote').value.trim());if(!e)return;document.getElementById('graphFrom').value='';document.getElementById('graphTo').value='';document.getElementById('graphNote').value='';renderGraph()}
function runAICore(){if(!window.AIOrchestrator)return;const value=thought.value.trim();const out=AIOrchestrator.orchestrate(value);document.getElementById('aiVersion').textContent=out.version;document.getElementById('aiPrimary').textContent=`${out.primaryAgent} · perspectiva primária`;document.getElementById('aiMandate').textContent=out.mandate;document.getElementById('aiRoute').innerHTML=out.route.ranking.map((x,i)=>`<div class="history-item"><b>${i+1}. ${AIOrchestrator.agents[x.agent].name}</b><span>score ${x.score}</span><small>${AIOrchestrator.agents[x.agent].focus}</small></div>`).join('');showPanel(aiCorePanel)}
document.getElementById('enter').onclick=()=>{runAICore();run('lumen')};document.getElementById('openCodex').onclick=()=>showPanel(codexPanel);document.querySelectorAll('.card').forEach(c=>c.onclick=()=>{const m=c.dataset.mode;if(m==='enigma')showPanel(enigmaPanel);else if(m==='lumen'){showPanel(lumenPanel);run('lumen')}else if(m==='translator')translateCurrent();else if(m==='graph'){showPanel(graphPanel);renderGraph()}else if(m==='ai-core')runAICore();else run(m)});saveCodex.onclick=saveCurrent;renderHistory();initTranslator();document.getElementById('translateText').onclick=translateCurrent;document.getElementById('connectGraph').onclick=connectGraph;
const startEnigma=document.getElementById('startEnigma'),hintEnigma=document.getElementById('hintEnigma'),checkEnigma=document.getElementById('checkEnigma'),answer=document.getElementById('enigmaAnswer'),feedback=document.getElementById('enigmaFeedback'),eid=document.getElementById('enigmaId'),ec=document.getElementById('enigmaCodename'),eq=document.getElementById('enigmaQuestion');let hintIndex=0;startEnigma.onclick=()=>{const e=EnigmaEngine.start();hintIndex=0;eid.textContent=e.id;ec.textContent=e.codename;eq.textContent=e.question;feedback.textContent='A chave foi aberta. Pense antes de responder.';answer.value='';showPanel(enigmaPanel)};hintEnigma.onclick=()=>{if(!EnigmaEngine.current){feedback.textContent='Abra um enigma primeiro.';return}feedback.textContent=EnigmaEngine.getHint(hintIndex++%EnigmaEngine.current.hints.length)};checkEnigma.onclick=()=>{const r=EnigmaEngine.evaluate(answer.value);feedback.textContent=r.feedback;if(r.correct)runLumen(thought.value.trim()||r.feedback)};
